modLoader="kotlinforforge"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/pearxteam/craftdumper/issues"
showAsResourcePack=false
logoFile="logo.png"
license = "GNU General Public License v3.0"

[[mods]]
  modId="craftdumper"
  version="${file.jarVersion}"
  displayName="CraftDumper"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/craftdumper"
  authors="mrapplexz"
  description='''
  A Minecraft Forge mod that can create dumps of various game stuff, such as blocks, items, entities and many more.
  '''

#  [[dependencies.craftdumper]]
#    modId="projecte"
#    versionRange="()"
#    mandatory=false
#    ordering="AFTER"
#    side="BOTH"